# Generated by Django 3.0 on 2020-07-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remindo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminders',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
