# Generated by Django 3.0 on 2020-07-21 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remindo', '0002_reminders_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminders',
            old_name='status',
            new_name='sent',
        ),
    ]
