# Generated by Django 3.0 on 2020-07-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remindo', '0005_auto_20200721_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminders',
            name='sent',
            field=models.CharField(choices=[('SEN', 'Sent'), ('FOC', 'Out Of Credit'), ('FID', 'Invalid Destination'), ('SCD', 'Scheduled')], default='SCD', max_length=3),
        ),
    ]
