# Generated by Django 3.0 on 2020-07-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remindo', '0006_auto_20200721_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visits',
            name='visitor',
        ),
    ]
