# Generated by Django 3.0 on 2020-07-22 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remindo', '0007_remove_visits_visitor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visits',
        ),
    ]
