# Generated by Django 3.0 on 2020-07-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200720_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=123, max_length=30),
            preserve_default=False,
        ),
    ]
