# Generated by Django 3.0 on 2020-07-20 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='referral',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
    ]
